-- App User
CREATE SEQUENCE IF NOT EXISTS public.ID_SEQ_APP_USER INCREMENT 1 START 1;
CREATE TABLE IF NOT EXISTS public.APP_USER(
    ID INTEGER PRIMARY KEY
);
ALTER TABLE public.APP_USER ADD COLUMN NAME CHARACTER VARYING;
ALTER TABLE public.APP_USER ADD COLUMN USERNAME CHARACTER VARYING;
ALTER TABLE public.APP_USER ADD COLUMN PASSWORD CHARACTER VARYING;
